### ISSUE TITLE
Remove custom analytics-specific configuration

### ISSUE THREAD

**Issue by peol** [qlik-oss/core-qix-session-workout#2]
Right now there is logic/configuration for how the authentication/JWT and entry point for the Custom Analytics deployment looks like. We should move this to some sort of configuration/scenario in the custom analytics repo, and run this tool against those files (similar to how after-work.js works).

This tool should be a generic tool that allows the user to:

* Implement their scenarios elsewhere
* Orchestrate clustering (master + slaves/runners)
* Monitor/summarize in realtime for all runners

We should think about how the default configuration should look like in terms of:

* The CLI configuration `direct` shouldn't be needed, should be in a config file for scenarios instead.
* Selections CLI should likely be implemented in scenarios instead.
* Headers should be generic configuration in the scenarios.
* Allow random seeding to increase reproducibility.

Example:

```
qix-session-workout --scenario ./my-scenario.js
<presents monitoring UI>
```

`my-scenario.js` here needs to have an API that bootstrap the master, as well as instruct which runner script all runners should use (and that script should get instructions from the master, e.g. which random seed to use, how many sessions to run, maybe other things like % of random selections etc.).

**Comment by janmiderback** [comment]
What more is left of this one when both #36 and #43 are done?

**Comment by peol** [comment]
@janmiderback I left a comment on #43 about my thoughts on it.

**Comment by janmiderback** [comment]
@peol good, but with those fixes suggested, you think this issue is still valid or should also be closed?

**Comment by wennmo** [comment]
Remaining items from #43:

There are a number of these left that should be scenario-specific in my opinion:

`--interactionInterval`, `--interactionRatio` — they are not generic enough to be top-level API.
`--keepAlive` — just make the scenario API return a promise which the workers resolve when they are done, and make it scenario-specific.
`--sessionLength` — perhaps `--workerTimeout` and leave the "length" to scenarios.
`--triangular` — I understand why this would be useful but perhaps it's more fitting as an example scenario and add top-level APIs needed to implement it?

Perhaps we should align the CLI naming too (i.e. each thread creates a number of workers, each worker gets a worker configuration based on CLI/scenario parameters [e.g. seed, timeout]). Workers open sessions.

**Comment by sublibra** [comment]
We consider the current scope to be enough for this present iteration. Closing this issue.
